### PR TITLE
Print out every event data on new line

### PR DESCRIPTION
**Pull request by simmel**
Originally by @i-maravic in #1

### CODE REVIEW

**Comment by simmel** [comment]
We have signed the CLA, 28 dec Mattias Nordström signed it for Stockholm University. And yes, I commited with the mail that was in the CLA.

**Comment by simmel** [comment]
This also unbreaks using the json codec which without this PR outputs everything on one line.

**Comment by jsvd** [comment]
Thanks for the contribution. This PR is a breaking change in behaviour, and since you can achieve the same using the line codec (`stdout { codec => line }`),  I don't think it should be merged.

**Comment by jsvd** [comment]
Thanks for the contribution. This PR is a breaking change in behaviour, if you're using a codec like `dots` you'll start seeing a dot in every line instead of a list of  dots, and there's no way to chose the current behaviour. Since you can achieve the same result using the line codec (`stdout { codec => line }`),  I don't think this should be merged.

**Comment by simmel** [comment]
Using `stdout { codec => line } }` only outputs the `message`-field.

`stdout { codec => json } }` outputs everything except `@metadata`.

**Comment by simmel** [comment]
Ah, using `stdout { codec => json_lines } }` works.

**Pull request closed without merging**
