### PR TITLE
remove awesome_print

### PR DESCRIPTION
**Pull request by colinsurprenant**
related to elastic/logstash#4123

I do not understand the reason for having awesome_print required here and it currently breaks `rake test:plugins` with

```
NoMethodError: undefined method `on_load' for ActiveSupport:Module
/Users/colin/dev/src/elasticsearch/logstash/vendor/bundle/jruby/1.9/gems/awesome_print-1.6.1/lib/awesome_print.rb:29:in `(root)'
/Users/colin/dev/src/elasticsearch/logstash/vendor/bundle/jruby/1.9/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/Users/colin/dev/src/elasticsearch/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-stdout-2.0.2/lib/logstash/outputs/stdout.rb:1:in `(root)'
/Users/colin/dev/src/elasticsearch/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-stdout-2.0.2/lib/logstash/outputs/stdout.rb:36:in `Stdout'
/Users/colin/dev/src/elasticsearch/logstash/vendor/bundle/jruby/1.9/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/Users/colin/dev/src/elasticsearch/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-stdout-2.0.2/lib/logstash/outputs/stdout.rb:34:in `(root)'
/Users/colin/dev/src/elasticsearch/logstash/vendor/bundle/jruby/1.9/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
file:/Users/colin/dev/src/elasticsearch/logstash/vendor/jruby/lib/jruby.jar!/jruby/kernel19/kernel.rb:13:in `require_relative'
/Users/colin/dev/src/elasticsearch/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-stdout-2.0.2/spec/spec_helper.rb:1:in `(root)'
/Users/colin/dev/src/elasticsearch/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-stdout-2.0.2/spec/spec_helper.rb:3:in `(root)'
/Users/colin/dev/src/elasticsearch/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-stdout-2.0.2/spec/outputs/stdout_spec.rb:1:in `(root)'
/Users/colin/dev/src/elasticsearch/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-stdout-2.0.2/spec/outputs/stdout_spec.rb:2:in `(root)'
/Users/colin/dev/src/elasticsearch/logstash/vendor/bundle/jruby/1.9/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1:in `(root)'
/Users/colin/dev/src/elasticsearch/logstash/vendor/bundle/jruby/1.9/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1105:in `load_spec_files'
/Users/colin/dev/src/elasticsearch/logstash/vendor/bundle/jruby/1.9/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1105:in `load_spec_files'
/Users/colin/dev/src/elasticsearch/logstash/vendor/bundle/jruby/1.9/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:96:in `setup'
/Users/colin/dev/src/elasticsearch/logstash/vendor/bundle/jruby/1.9/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:84:in `run'
/Users/colin/dev/src/elasticsearch/logstash/vendor/bundle/jruby/1.9/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:69:in `run'
/Users/colin/dev/src/elasticsearch/logstash/rakelib/test.rake:72:in `(root)'
```

### CODE REVIEW

**Comment by jsvd** [comment]
LGTM

**Comment by jordansissel** [comment]
Posthumous LGTM.

:P

**Comment by colinsurprenant** [comment]
I will postunanimously merge.

**Comment by jsvd** [comment]
Posthumurous lol

**Comment by colinsurprenant** [comment]
post hummus.

**Comment by colinsurprenant** [comment]
forgot to bump version. will merge and :shipit:

**Comment by colinsurprenant** [comment]
published 2.0.3

**Pull request merged**
